--Insert into historical weather table
INSERT INTO weather (city_id,city_name,country,local_date,utc_recorded_at,tz_offset_hours,lat,lon,weather_type,weather_desc,measure_units,visibility_pct,cloud_pct,temp_deg,humidity_pct,pressure,temp_min,temp_max,feels_like,wind_deg,wind_gust,wind_speed)
SELECT city_id,   
	city_name,
	country,
	DATE(utc_recorded_at+tz_offset_hours),
	utc_recorded_at,
	tz_offset_hours,
	lat,
	lon,
	weather_type,
	weather_desc,
	measure_units,
	visibility_pct,
	cloud_pct,
	temp_deg,
	humidity_pct,
	pressure,
	temp_min,
	temp_max,
	feels_like,
	wind_deg,
	wind_gust,
	wind_speed
FROM current_weather

ON CONFLICT (city_id, utc_recorded_at) 
DO UPDATE SET lat = EXCLUDED.lat,
	lon = EXCLUDED.lon,
	weather_type = EXCLUDED.weather_type,
	weather_desc = EXCLUDED.weather_desc,
	measure_units = EXCLUDED.measure_units,
	visibility_pct = EXCLUDED.visibility_pct,
	cloud_pct = EXCLUDED.cloud_pct,
	temp_deg = EXCLUDED.temp_deg,
	humidity_pct = EXCLUDED.humidity_pct,
	pressure = EXCLUDED.pressure,
	temp_min = EXCLUDED.temp_min,
	temp_max = EXCLUDED.temp_max,
	feels_like = EXCLUDED.feels_like,
	wind_deg = EXCLUDED.wind_deg,
	wind_gust = EXCLUDED.wind_gust,
	wind_speed = EXCLUDED.wind_speed;